ALTER TABLE households ADD COLUMN timezone TEXT NOT NULL DEFAULT '';

CREATE TABLE planning_goals (
    id TEXT NOT NULL PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    owner_user_id TEXT NOT NULL REFERENCES users(id),
    visibility TEXT NOT NULL CHECK(visibility IN ('personal','shared')),
    source_id TEXT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    source_family TEXT NOT NULL CHECK(source_family IN ('text','voice','csv','xlsx','pdf')),
    source_version INTEGER NOT NULL CHECK(source_version > 0),
    title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 256),
    target_on TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL CHECK(status IN ('active','completed','cancelled')) DEFAULT 'active',
    generated_by TEXT NOT NULL CHECK(generated_by IN ('application','ai','user')),
    schema_version TEXT NOT NULL CHECK(length(schema_version) BETWEEN 1 AND 64),
    data_revision INTEGER NOT NULL CHECK(data_revision >= 0), active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), version INTEGER NOT NULL DEFAULT 1 CHECK(version>0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE planning_plans (
    id TEXT NOT NULL PRIMARY KEY, household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE, owner_user_id TEXT NOT NULL REFERENCES users(id), visibility TEXT NOT NULL CHECK(visibility IN ('personal','shared')),
    source_id TEXT NOT NULL REFERENCES sources(id) ON DELETE CASCADE, source_family TEXT NOT NULL CHECK(source_family IN ('text','voice','csv','xlsx','pdf')), source_version INTEGER NOT NULL CHECK(source_version>0),
    goal_id TEXT REFERENCES planning_goals(id), title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 256), status TEXT NOT NULL CHECK(status IN ('active','completed','cancelled')) DEFAULT 'active', generated_by TEXT NOT NULL CHECK(generated_by IN ('application','ai','user')), schema_version TEXT NOT NULL CHECK(length(schema_version) BETWEEN 1 AND 64), data_revision INTEGER NOT NULL CHECK(data_revision>=0), active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), version INTEGER NOT NULL DEFAULT 1 CHECK(version>0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE planning_milestones (
    id TEXT NOT NULL PRIMARY KEY, household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE, owner_user_id TEXT NOT NULL REFERENCES users(id), visibility TEXT NOT NULL CHECK(visibility IN ('personal','shared')),
    source_id TEXT NOT NULL REFERENCES sources(id) ON DELETE CASCADE, source_family TEXT NOT NULL CHECK(source_family IN ('text','voice','csv','xlsx','pdf')), source_version INTEGER NOT NULL CHECK(source_version>0),
    plan_id TEXT NOT NULL REFERENCES planning_plans(id) ON DELETE CASCADE, title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 256), due_on TEXT NOT NULL DEFAULT '', status TEXT NOT NULL CHECK(status IN ('open','completed','cancelled')) DEFAULT 'open', generated_by TEXT NOT NULL CHECK(generated_by IN ('application','ai','user')), schema_version TEXT NOT NULL CHECK(length(schema_version) BETWEEN 1 AND 64), data_revision INTEGER NOT NULL CHECK(data_revision>=0), active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), version INTEGER NOT NULL DEFAULT 1 CHECK(version>0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE planning_events (
    id TEXT NOT NULL PRIMARY KEY, household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE, owner_user_id TEXT NOT NULL REFERENCES users(id), visibility TEXT NOT NULL CHECK(visibility IN ('personal','shared')),
    source_id TEXT NOT NULL REFERENCES sources(id) ON DELETE CASCADE, source_family TEXT NOT NULL CHECK(source_family IN ('text','voice','csv','xlsx','pdf')), source_version INTEGER NOT NULL CHECK(source_version>0),
    plan_id TEXT REFERENCES planning_plans(id) ON DELETE SET NULL, milestone_id TEXT REFERENCES planning_milestones(id) ON DELETE SET NULL, title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 256), description TEXT NOT NULL DEFAULT '' CHECK(length(description)<=4000), location TEXT NOT NULL DEFAULT '' CHECK(length(location)<=512), all_day INTEGER NOT NULL CHECK(all_day IN (0,1)), starts_on TEXT NOT NULL DEFAULT '', ends_on TEXT NOT NULL DEFAULT '', starts_at TEXT NOT NULL DEFAULT '', ends_at TEXT NOT NULL DEFAULT '', timezone TEXT NOT NULL DEFAULT '', status TEXT NOT NULL CHECK(status IN ('planned','completed','cancelled')) DEFAULT 'planned', generated_by TEXT NOT NULL CHECK(generated_by IN ('application','ai','user')), schema_version TEXT NOT NULL CHECK(length(schema_version) BETWEEN 1 AND 64), data_revision INTEGER NOT NULL CHECK(data_revision>=0), active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), version INTEGER NOT NULL DEFAULT 1 CHECK(version>0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
    CHECK((all_day=1 AND starts_on<>'' AND (ends_on='' OR ends_on>=starts_on) AND starts_at='' AND ends_at='' AND timezone='') OR (all_day=0 AND starts_on='' AND ends_on='' AND starts_at<>'' AND ends_at>starts_at AND timezone<>''))
);
CREATE TABLE planning_event_owners (event_id TEXT NOT NULL REFERENCES planning_events(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id), PRIMARY KEY(event_id,user_id));
CREATE TABLE planning_dependencies (id TEXT NOT NULL PRIMARY KEY, event_id TEXT NOT NULL REFERENCES planning_events(id) ON DELETE CASCADE, depends_on_event_id TEXT NOT NULL REFERENCES planning_events(id) ON DELETE CASCADE, CHECK(event_id<>depends_on_event_id), UNIQUE(event_id,depends_on_event_id));
CREATE TABLE planning_constraints (id TEXT NOT NULL PRIMARY KEY, event_id TEXT NOT NULL REFERENCES planning_events(id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK(length(kind) BETWEEN 1 AND 64), value TEXT NOT NULL CHECK(length(value) BETWEEN 1 AND 512), UNIQUE(event_id,kind,value));
CREATE TABLE planning_completion_states (event_id TEXT NOT NULL PRIMARY KEY REFERENCES planning_events(id) ON DELETE CASCADE, completed_at TEXT NOT NULL, completed_by_user_id TEXT NOT NULL REFERENCES users(id));

CREATE INDEX planning_events_calendar ON planning_events(household_id,visibility,owner_user_id,active,status,starts_on,starts_at,ends_on,ends_at);
CREATE INDEX planning_event_owners_event ON planning_event_owners(event_id,user_id);
CREATE INDEX planning_dependencies_event ON planning_dependencies(event_id,depends_on_event_id);

CREATE TRIGGER planning_goal_scope_insert BEFORE INSERT ON planning_goals WHEN NOT EXISTS (SELECT 1 FROM household_members m JOIN users u ON u.id=m.user_id JOIN households h ON h.id=m.household_id WHERE m.household_id=NEW.household_id AND m.user_id=NEW.owner_user_id AND u.status='active' AND h.status='active') OR NOT EXISTS (SELECT 1 FROM sources s WHERE s.id=NEW.source_id AND s.household_id=NEW.household_id AND s.family=NEW.source_family AND s.source_version=NEW.source_version AND s.state='live' AND (s.visibility='shared' OR (s.visibility='personal' AND s.owner_user_id=NEW.owner_user_id AND NEW.visibility='personal'))) BEGIN SELECT RAISE(ABORT,'invalid planning scope'); END;
CREATE TRIGGER planning_plan_scope_insert BEFORE INSERT ON planning_plans WHEN NOT EXISTS (SELECT 1 FROM household_members m JOIN users u ON u.id=m.user_id JOIN households h ON h.id=m.household_id WHERE m.household_id=NEW.household_id AND m.user_id=NEW.owner_user_id AND u.status='active' AND h.status='active') OR NOT EXISTS (SELECT 1 FROM planning_goals g WHERE (NEW.goal_id IS NULL OR (g.id=NEW.goal_id AND g.household_id=NEW.household_id AND g.visibility=NEW.visibility AND g.active=1))) OR NOT EXISTS (SELECT 1 FROM sources s WHERE s.id=NEW.source_id AND s.household_id=NEW.household_id AND s.family=NEW.source_family AND s.source_version=NEW.source_version AND s.state='live' AND (s.visibility='shared' OR (s.visibility='personal' AND s.owner_user_id=NEW.owner_user_id AND NEW.visibility='personal'))) BEGIN SELECT RAISE(ABORT,'invalid planning plan scope'); END;
CREATE TRIGGER planning_milestone_scope_insert BEFORE INSERT ON planning_milestones WHEN NOT EXISTS (SELECT 1 FROM household_members m JOIN users u ON u.id=m.user_id JOIN households h ON h.id=m.household_id WHERE m.household_id=NEW.household_id AND m.user_id=NEW.owner_user_id AND u.status='active' AND h.status='active') OR NOT EXISTS (SELECT 1 FROM planning_plans p WHERE p.id=NEW.plan_id AND p.household_id=NEW.household_id AND p.visibility=NEW.visibility AND p.active=1) OR NOT EXISTS (SELECT 1 FROM sources s WHERE s.id=NEW.source_id AND s.household_id=NEW.household_id AND s.family=NEW.source_family AND s.source_version=NEW.source_version AND s.state='live' AND (s.visibility='shared' OR (s.visibility='personal' AND s.owner_user_id=NEW.owner_user_id AND NEW.visibility='personal'))) BEGIN SELECT RAISE(ABORT,'invalid planning milestone scope'); END;
CREATE TRIGGER planning_event_scope_insert BEFORE INSERT ON planning_events WHEN NOT EXISTS (SELECT 1 FROM household_members m JOIN users u ON u.id=m.user_id JOIN households h ON h.id=m.household_id WHERE m.household_id=NEW.household_id AND m.user_id=NEW.owner_user_id AND u.status='active' AND h.status='active') OR NOT EXISTS (SELECT 1 FROM sources s WHERE s.id=NEW.source_id AND s.household_id=NEW.household_id AND s.family=NEW.source_family AND s.source_version=NEW.source_version AND s.state='live' AND (s.visibility='shared' OR (s.visibility='personal' AND s.owner_user_id=NEW.owner_user_id AND NEW.visibility='personal'))) OR NOT EXISTS (SELECT 1 WHERE NEW.plan_id IS NULL OR EXISTS(SELECT 1 FROM planning_plans p WHERE p.id=NEW.plan_id AND p.household_id=NEW.household_id AND p.visibility=NEW.visibility AND p.active=1)) OR NOT EXISTS (SELECT 1 WHERE NEW.milestone_id IS NULL OR EXISTS(SELECT 1 FROM planning_milestones m WHERE m.id=NEW.milestone_id AND m.household_id=NEW.household_id AND m.visibility=NEW.visibility AND m.active=1)) BEGIN SELECT RAISE(ABORT,'invalid planning event scope'); END;

CREATE TRIGGER planning_event_owner_scope BEFORE INSERT ON planning_event_owners WHEN NOT EXISTS (SELECT 1 FROM planning_events e JOIN household_members m ON m.household_id=e.household_id AND m.user_id=NEW.user_id JOIN users u ON u.id=NEW.user_id WHERE e.id=NEW.event_id AND e.active=1 AND u.status='active') BEGIN SELECT RAISE(ABORT,'invalid event owner'); END;
CREATE TRIGGER planning_dependency_scope BEFORE INSERT ON planning_dependencies WHEN NOT EXISTS (SELECT 1 FROM planning_events a JOIN planning_events b ON b.id=NEW.depends_on_event_id WHERE a.id=NEW.event_id AND a.household_id=b.household_id AND a.visibility=b.visibility AND a.active=1 AND b.active=1) BEGIN SELECT RAISE(ABORT,'invalid event dependency'); END;
CREATE TRIGGER planning_completion_scope BEFORE INSERT ON planning_completion_states WHEN NOT EXISTS (SELECT 1 FROM planning_events e JOIN household_members m ON m.household_id=e.household_id AND m.user_id=NEW.completed_by_user_id JOIN users u ON u.id=NEW.completed_by_user_id WHERE e.id=NEW.event_id AND e.active=1 AND u.status='active') BEGIN SELECT RAISE(ABORT,'invalid completion state'); END;

CREATE TRIGGER planning_event_revision AFTER INSERT ON planning_events BEGIN UPDATE household_revisions SET shared_revision=shared_revision+1 WHERE household_id=NEW.household_id AND NEW.visibility='shared'; UPDATE user_revisions SET personal_revision=personal_revision+1 WHERE user_id=NEW.owner_user_id AND NEW.visibility='personal'; END;
CREATE TRIGGER planning_goal_revision AFTER INSERT ON planning_goals BEGIN UPDATE household_revisions SET shared_revision=shared_revision+1 WHERE household_id=NEW.household_id AND NEW.visibility='shared'; UPDATE user_revisions SET personal_revision=personal_revision+1 WHERE user_id=NEW.owner_user_id AND NEW.visibility='personal'; END;
CREATE TRIGGER planning_plan_revision AFTER INSERT ON planning_plans BEGIN UPDATE household_revisions SET shared_revision=shared_revision+1 WHERE household_id=NEW.household_id AND NEW.visibility='shared'; UPDATE user_revisions SET personal_revision=personal_revision+1 WHERE user_id=NEW.owner_user_id AND NEW.visibility='personal'; END;
CREATE TRIGGER planning_milestone_revision AFTER INSERT ON planning_milestones BEGIN UPDATE household_revisions SET shared_revision=shared_revision+1 WHERE household_id=NEW.household_id AND NEW.visibility='shared'; UPDATE user_revisions SET personal_revision=personal_revision+1 WHERE user_id=NEW.owner_user_id AND NEW.visibility='personal'; END;
CREATE TRIGGER planning_goals_immutable BEFORE UPDATE OF id,household_id,owner_user_id,visibility,source_id,source_family,source_version,generated_by,schema_version,data_revision,created_at ON planning_goals BEGIN SELECT RAISE(ABORT,'planning scope is immutable'); END;
CREATE TRIGGER planning_plans_immutable BEFORE UPDATE OF id,household_id,owner_user_id,visibility,source_id,source_family,source_version,goal_id,generated_by,schema_version,data_revision,created_at ON planning_plans BEGIN SELECT RAISE(ABORT,'planning scope is immutable'); END;
CREATE TRIGGER planning_milestones_immutable BEFORE UPDATE OF id,household_id,owner_user_id,visibility,source_id,source_family,source_version,plan_id,generated_by,schema_version,data_revision,created_at ON planning_milestones BEGIN SELECT RAISE(ABORT,'planning scope is immutable'); END;
CREATE TRIGGER planning_events_immutable BEFORE UPDATE OF id,household_id,owner_user_id,visibility,source_id,source_family,source_version,plan_id,milestone_id,generated_by,schema_version,data_revision,created_at ON planning_events BEGIN SELECT RAISE(ABORT,'planning scope is immutable'); END;
CREATE TRIGGER planning_event_change_revision AFTER UPDATE OF active,version,status ON planning_events WHEN OLD.active<>NEW.active OR OLD.version<>NEW.version OR OLD.status<>NEW.status BEGIN UPDATE household_revisions SET shared_revision=shared_revision+1 WHERE household_id=NEW.household_id AND NEW.visibility='shared'; UPDATE user_revisions SET personal_revision=personal_revision+1 WHERE user_id=NEW.owner_user_id AND NEW.visibility='personal'; END;
CREATE TRIGGER planning_events_search_delete AFTER DELETE ON planning_events BEGIN DELETE FROM search_entries WHERE record_family='planning' AND record_id=OLD.id; END;
CREATE TRIGGER planning_goals_search_delete AFTER DELETE ON planning_goals BEGIN DELETE FROM search_entries WHERE record_family='planning' AND record_id=OLD.id; END;
CREATE TRIGGER planning_plans_search_delete AFTER DELETE ON planning_plans BEGIN DELETE FROM search_entries WHERE record_family='planning' AND record_id=OLD.id; END;
CREATE TRIGGER planning_milestones_search_delete AFTER DELETE ON planning_milestones BEGIN DELETE FROM search_entries WHERE record_family='planning' AND record_id=OLD.id; END;
